// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ro.rmc.bugtracker.domain;

import org.springframework.beans.factory.annotation.Configurable;
import ro.rmc.bugtracker.domain.ProductDataOnDemand;

privileged aspect ProductDataOnDemand_Roo_Configurable {
    
    declare @type: ProductDataOnDemand: @Configurable;
    
}
